database:
    # database name
    database: "minecraft"
    # host
    host: "localhost"
    # port
    port: 3306
    # login username
    username: "root"
    # login password
    password: ""
    # database type
    # only MYSQL is supported actually
    type: MYSQL