name: ${project.name}
main: ${groupId}.CoreMain
version: ${project.version}
author: emanon
api-version: 1.13
softdepend: [SuperVanish,PremiumVanish,PlaceholderAPI,VirginBlock,Vault,ProtocolLib,CMI,Towny,ItemEdit,MythicMobs,DracarysGui]