# use multiple languages or stick to default locale for everyone?
use-multi-language: false
# default locale file used
default-locale: "en"
# use-multi-language is true but you want to limit languages?
# put limits here on which locale may be used, if a player use an unallowed locale default locale will be used
allowed-languages:
    # list of locales
    list: []
    # use previus list as a whitelist ?
    is-whitelist: false